### ISSUE TITLE
Delete this repository as the same content is on SwissTPH/openmalaria.wiki

### ISSUE THREAD

**Issue by tph-thuering** [vecnet/om_schema_docs#1]
__People might be confused to see it here and edit the wiki on the wrong repository.__

Since openmalaria has moved to github recently, we should link only to that.
I've updated all links to GeneratedDocs, so they point to the SwissTPH/openmalaria.wiki rather than here (vecnet).

@Baguage @sgtbigman : as we talked about a few weeks ago, I have added the GeneratedDocs to the openmalaria wiki itself. Please update your links to SwissTPH's wiki and maybe delete this repo if it is not used anymore to reduce some redundancy and user confusion.

**Comment by sgtbigman** [comment]
@tph-thuering Sounds good. I'll update the links and delete the repo when I get the chance.

**Comment by dhardy** [comment]
FYI the only reason the generated docs are in their own repo is that at the time, the main OM wiki was on Google Code, which didn't handle the generated docs properly. The wikis could probably be combined now.

On Tue Jun 2 16:39:47 2015 GMT+0100, Tobias Thüring wrote:
> __People might be confused to see it here and edit the wiki on the wrong repository.__
> 
> Since openmalaria has moved to github recently, we should link only to that.
> I've updated all links to GeneratedDocs, so they point to the SwissTPH/openmalaria.wiki rather than here (vecnet).
> 
> @Baguage @sgtbigman : as we talked about a few weeks ago, I have added the GeneratedDocs to the openmalaria wiki itself. Please update your links to SwissTPH's wiki and maybe delete this repo if it is not used anymore to reduce some redundancy and user confusion.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vecnet/om_schema_docs/issues/

-- 
Sent from my Jolla

**Comment by sgtbigman** [comment]
Agreed. I edited the repo description to reflect that it will be removed soon. Once I update the links in the VecNet project and push those changes to the website, I'll remove this repository.

**Comment by tph-thuering** [comment]
@dhardy :+1:
@sgtbigman kthxbye :smiley:

**Comment by Baguage** [comment]
Who was that ghost user???

Just a side note - there are links to om_schema_docs repository in comments too (description of different attributes). It is necessary to update them too before deleting this repository.

**Comment by tph-thuering** [comment]
@Baguage I don't know a ghost...

I realize this, so please update them. :+1: 

Thank you

**Comment by tph-thuering** [comment]
@Baguage Did you mean on the openmalaria wiki? I think I did already do this on the SwissTPH repo's

**Comment by sgtbigman** [comment]
@Baguage Sorry, that ghost was me; I made a more 'formal' account, but then changed my mind. :stuck_out_tongue:

**Comment by Baguage** [comment]
@tph-thuering no, I mean comments in vecnet.openmalaria source code. I put a lot of links to om_schema_docs (instead of copy-pasting descriptions), and they either should be updated or removed if the repository is going away.

@sgtbigman got it, I was afraid someone hacked our github site :smile: (one never knows, do one?)

**Comment by sgtbigman** [comment]
@Baguage I'll update the vecnet.openmalaria repo with those changes as soon as possible. I already made the necessary changes to ts_om, but those will need to be pushed to ci before we can delete this repository.

**Comment by tph-thuering** [comment]
@Baguage Please merge my pull request: https://github.com/vecnet/vecnet.openmalaria/pull/35

**Comment by Baguage** [comment]
@sgtbigman can you check that pull request and merge it for me if links work? https://github.com/vecnet/vecnet.openmalaria/pull/35

**Comment by nicolasreed** [comment]
All links now point to the SwissTPH/openmalaria wiki. This repository will be deleted.
